In [30]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json

# Manipulating the data

## Read json file

In [31]:
# Path: data/fragances.json
# Opening JSON file
f = open("../data/fragances.json", encoding="utf8")

# returns JSON object as 
# a dictionary
data = json.load(f)

In [32]:
def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if type(x) is dict:
            for a in x:
                flatten(x[a], name + a + '_')
        elif type(x) is list:
            i = 0
            for a in x:
                flatten(a, name + str(i) + '_')
                i += 1
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

In [33]:
for i in range(len(data)):
    data[i] = flatten_json(data[i])
df = pd.DataFrame(data)
df.head()

,_id_$oid,idNumber,name,designer,official_gender,rating,votes,seasons_winter,seasons_summer,seasons_autumn,...,base_notes_17,base_notes_18,base_notes_19,middle_notes_16,base_notes_20,base_notes_21,base_notes_22,base_notes_23,top_notes_14,top_notes_15
0,6536bfd623ce6e4d819f5f06,1,Couture! Moschino perfume - a fragrance for wo...,Moschino,for women,4.21,1627,38,14,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6536c06c23ce6e4d819f5f0a,2,Friends Men Moschino cologne - a fragrance for...,Moschino,for men,3.92,499,4,19,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6536c06d23ce6e4d819f5f0c,3,Moschino Moschino perfume - a fragrance for wo...,Moschino,for women,3.98,1267,43,9,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6536c06e23ce6e4d819f5f0e,4,Moschino Funny! Moschino perfume - a fragrance...,Moschino,for women,3.98,6375,7,74,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6536c06f23ce6e4d819f5f10,5,Moschino Pour Homme Moschino cologne - a fragr...,Moschino,for men,4.34,256,9,2,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.to_csv('../data/fragances.csv', index=False)